
SELECT TOP 3 C.CustomerID, C.FirstName, C.LastName , COUNT (O.OrderID) AS CUSTOMERORDERCOUNT
FROM Customers C INNER JOIN Orders O on C.CUSTOMERID = O.CUSTOMERID 
GROUP BY C.CUSTOMERID
ORDER BY COUNT(O.OrderID) DESC;
